# Generated by Django 5.1 on 2024-12-23 00:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedimage',
            name='encrypted_key_for_owner',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encryptedimage',
            name='encrypted_key_iv',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encryptedimage',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='encryptedimage',
            name='pass_key_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='encryptedimage',
            name='pass_key_salt',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='encryptedimage',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
